name: Clang format check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
         repository: arduino/tooling-project-assets
         path: atpa
    
    - name: Copy the clang format
      run: |
        cp "./atpa/other/clang-format-configuration/.clang-format" "./.clang-format"
        rm -r "./atpa"
        # chmod 777 "./.clang-format"

    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '14'
        exclude-regex: '(apta|res)'
        
