name: Clang format check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -e "icons.c" -e "font_AwesomeF000.c" -r . 
