name: Clang format check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
         repository: Sarcasm/run-clang-format
         path: ci
    - name: Copy the clang format
      run: |
        cp "./scripts/.clang-format" "./.clang-format"
        # chmod 777 "./.clang-format"

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -e "./res/*" --extensions "ino" --style "file:./.clang-format" -r . 
